export const movies = {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg",
        genre_ids: [28, 878, 14],
        id: 526896,
        original_language: "en",
        original_title: "Morbius",
        poster_path: "/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
        title: "Morbius",
        video: false,
        vote_average: 6.3,
        overview:
          "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
        release_date: "2022-03-30",
        vote_count: 995,
        popularity: 8853.551,
        media_type: "movie",
      },
      {
        overview:
          "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
        release_date: "2022-04-07",
        adult: false,
        backdrop_path: "/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg",
        id: 639933,
        genre_ids: [28, 12, 14, 53],
        original_language: "en",
        original_title: "The Northman",
        poster_path: "/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg",
        vote_count: 1011,
        video: false,
        vote_average: 7.5,
        title: "The Northman",
        popularity: 6992.273,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg",
        genre_ids: [14, 28, 12],
        id: 453395,
        original_language: "en",
        original_title: "Doctor Strange in the Multiverse of Madness",
        poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
        title: "Doctor Strange in the Multiverse of Madness",
        video: false,
        vote_average: 7.4,
        overview:
          "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
        release_date: "2022-05-04",
        vote_count: 1748,
        popularity: 3368.831,
        media_type: "movie",
      },
      {
        genre_ids: [28, 878, 35, 10751, 12],
        original_language: "en",
        original_title: "Sonic the Hedgehog 2",
        poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
        id: 675353,
        video: false,
        title: "Sonic the Hedgehog 2",
        overview:
          "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
        release_date: "2022-03-30",
        vote_count: 1536,
        adult: false,
        backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
        vote_average: 7.8,
        popularity: 7843.215,
        media_type: "movie",
      },
      {
        video: false,
        title: "The Batman",
        id: 414906,
        overview:
          "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
        release_date: "2022-03-01",
        adult: false,
        backdrop_path: "/xHrp2pq73oi9D64xigPjWW1wcz1.jpg",
        genre_ids: [80, 9648, 53],
        vote_count: 4693,
        original_language: "en",
        original_title: "The Batman",
        poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        vote_average: 7.8,
        popularity: 3497.925,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg",
        genre_ids: [28, 12, 35, 10749],
        title: "The Lost City",
        original_language: "en",
        original_title: "The Lost City",
        poster_path: "/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
        id: 752623,
        video: false,
        vote_average: 6.7,
        overview:
          "A reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
        release_date: "2022-03-24",
        vote_count: 683,
        popularity: 10211.875,
        media_type: "movie",
      },
      {
        release_date: "2022-03-24",
        adult: false,
        backdrop_path: "/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
        id: 545611,
        genre_ids: [28, 12, 878, 35],
        original_language: "en",
        original_title: "Everything Everywhere All at Once",
        poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        vote_count: 284,
        video: false,
        vote_average: 8.7,
        title: "Everything Everywhere All at Once",
        overview:
          "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
        popularity: 335.704,
        media_type: "movie",
      },
      {
        vote_average: 7.2,
        overview:
          "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
        release_date: "2022-02-10",
        id: 335787,
        adult: false,
        backdrop_path: "/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg",
        genre_ids: [28, 12],
        vote_count: 2047,
        original_language: "en",
        original_title: "Uncharted",
        poster_path: "/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
        title: "Uncharted",
        video: false,
        popularity: 3767.836,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/qK7Ssnrfvrt65F66A1thvehfQg2.jpg",
        genre_ids: [16, 10751, 35, 12, 14, 9648],
        id: 420821,
        original_language: "en",
        original_title: "Chip 'n Dale: Rescue Rangers",
        overview:
          "Decades since their successful television series was canceled, Chip has succumbed to a life of suburban domesticity as an insurance salesman. Dale, meanwhile, has had CGI surgery and works the nostalgia convention circuit, desperate to relive his glory days. When a former cast mate mysteriously disappears, Chip and Dale must repair their broken friendship and take on their Rescue Rangers detective personas once again to save their friend’s life.",
        poster_path: "/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg",
        release_date: "2022-05-20",
        title: "Chip 'n Dale: Rescue Rangers",
        video: false,
        vote_average: 7.3,
        vote_count: 86,
        popularity: 123.033,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/kiH3KPWi7BaRMvdAigcwrUFViHl.jpg",
        genre_ids: [9648, 53, 28, 80],
        id: 818397,
        original_language: "en",
        original_title: "Memory",
        poster_path: "/tXpLmtnArbGcE75iPJVYibW7BBf.jpg",
        title: "Memory",
        video: false,
        vote_average: 7.1,
        overview:
          "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
        release_date: "2022-04-28",
        vote_count: 56,
        popularity: 165.203,
        media_type: "movie",
      },
      {
        release_date: "2022-04-06",
        adult: false,
        backdrop_path: "/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
        id: 338953,
        genre_ids: [28, 12, 14],
        original_language: "en",
        original_title: "Fantastic Beasts: The Secrets of Dumbledore",
        poster_path: "/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
        vote_count: 1067,
        video: false,
        vote_average: 6.7,
        title: "Fantastic Beasts: The Secrets of Dumbledore",
        overview:
          "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
        popularity: 954.7,
        media_type: "movie",
      },
      {
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        id: 634649,
        video: false,
        vote_average: 8.1,
        overview:
          "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        release_date: "2021-12-15",
        title: "Spider-Man: No Way Home",
        adult: false,
        backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
        vote_count: 12927,
        genre_ids: [28, 12, 878],
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        popularity: 3243.224,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
        genre_ids: [16, 35, 28, 10751, 80],
        vote_count: 465,
        original_language: "en",
        original_title: "The Bad Guys",
        id: 629542,
        title: "The Bad Guys",
        video: false,
        vote_average: 7.8,
        poster_path: "/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
        overview:
          "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
        release_date: "2022-03-17",
        popularity: 3284.364,
        media_type: "movie",
      },
      {
        backdrop_path: "/bIFrsAcqkLUUxaaiqqpFexYPeCh.jpg",
        genre_ids: [53, 14, 27],
        original_language: "en",
        original_title: "Firestarter",
        poster_path: "/2MTGip0nfahQ1jPQCZSfCsPBZes.jpg",
        video: false,
        vote_average: 6.4,
        vote_count: 152,
        overview:
          "For more than a decade, parents Andy and Vicky have been on the run, desperate to hide their daughter Charlie from a shadowy federal agency that wants to harness her unprecedented gift for creating fire into a weapon of mass destruction. Andy has taught Charlie how to defuse her power, which is triggered by anger or pain. But as Charlie turns 11, the fire becomes harder and harder to control. After an incident reveals the family's location, a mysterious operative is deployed to hunt down the family and seize Charlie once and for all. Charlie has other plans.",
        release_date: "2022-05-12",
        title: "Firestarter",
        id: 532710,
        adult: false,
        popularity: 195.276,
        media_type: "movie",
      },
      {
        overview:
          "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
        release_date: "2022-04-27",
        title: "365 Days: This Day",
        adult: false,
        backdrop_path: "/t9hNIUFcy0tYu55IPxjxRTTdZ6X.jpg",
        genre_ids: [10749, 18],
        original_language: "en",
        original_title: "365 Days: This Day",
        poster_path: "/7qU0SOVcQ8BTJLodcAlulUAG16C.jpg",
        vote_count: 431,
        video: false,
        vote_average: 5.6,
        id: 829557,
        popularity: 1185.545,
        media_type: "movie",
      },
      {
        genre_ids: [10752, 36, 18],
        original_language: "en",
        original_title: "Operation Mincemeat",
        poster_path: "/tfdfh1mK24VujxT5z11732asxdR.jpg",
        title: "Operation Mincemeat",
        video: false,
        vote_average: 6.7,
        overview:
          "In 1943, two British intelligence officers concoct Operation Mincemeat, wherein their plan to drop a corpse with false papers off the coast of Spain would fool Nazi spies into believing the Allied forces were planning to attack by way of Greece rather than Sicily.",
        id: 661231,
        vote_count: 140,
        release_date: "2022-04-01",
        adult: false,
        backdrop_path: "/oZtoyj3rhOST8FUtIXUqblIYmCv.jpg",
        popularity: 473.266,
        media_type: "movie",
      },
      {
        vote_average: 6.0,
        id: 800937,
        overview:
          "A thirty-seven-year-old woman wakes up from a twenty-year coma and returns to the high school where she was once a popular cheerleader to finish her senior year and become prom queen. The main plot is the empowerment of LGBTQ rights and progress through the years.",
        release_date: "2022-05-11",
        adult: false,
        backdrop_path: "/3FJ53wbpjSAGY98KYiHJ4DQccDr.jpg",
        genre_ids: [35, 18],
        vote_count: 206,
        original_language: "en",
        original_title: "Senior Year",
        poster_path: "/6UqbcDQhCYpxboK58Z0eVfdeHcT.jpg",
        title: "Senior Year",
        video: false,
        popularity: 824.641,
        media_type: "movie",
      },
      {
        overview:
          "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
        release_date: "2022-03-16",
        title: "Ambulance",
        adult: false,
        backdrop_path: "/dW3fQJrshh2wYDoW4HUA7ZabsN1.jpg",
        genre_ids: [28, 53, 80],
        original_language: "en",
        original_title: "Ambulance",
        poster_path: "/zT5ynZ0UR6HFfWQSRf2uKtqCyWD.jpg",
        vote_count: 621,
        video: false,
        vote_average: 7.0,
        id: 763285,
        popularity: 1920.885,
        media_type: "movie",
      },
      {
        adult: false,
        backdrop_path: "/kB1Qrsg189eDz4Ej3ABXtLudClq.jpg",
        genre_ids: [35],
        vote_count: 34,
        original_language: "en",
        original_title: "The Valet",
        id: 810171,
        title: "The Valet",
        video: false,
        vote_average: 7.3,
        poster_path: "/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg",
        overview:
          "World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia’s new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.",
        release_date: "2022-05-11",
        popularity: 96.148,
        media_type: "movie",
      },
      {
        poster_path: "/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
        video: false,
        vote_average: 6.5,
        overview:
          "A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
        release_date: "2022-02-03",
        vote_count: 1065,
        adult: false,
        backdrop_path: "/9Ngw106BLlNJ4iVpRHlrDfaLpCV.jpg",
        id: 406759,
        genre_ids: [878, 12, 28],
        title: "Moonfall",
        original_language: "en",
        original_title: "Moonfall",
        popularity: 2366.599,
        media_type: "movie",
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  };
  